users:
  name_length: 50
  email_length: 255
  pass_min_length: 6
  phone_min: 10
  phone_max: 15
  per_page: 10
conditions:
  checked: "1"
products:
  per_page: 12
  hot_page: 8
  fake_sale: 1.5
  max_stars: 5
  round: 2
  name_length: 50
cart:
  per_page: 3
  size_img: "50x50"
